# --- 网站核心配置 ---
baseURL = "https://Wz676.github.io/Eco.voces/"
languageCode = "es-VE"
title = "Muro de reciclaje "
theme = "blowfish"

# --- 关键系统工程配置 ---
# 这里指定生成的网页放入 docs 文件夹，以适配 GitHub Pages
publishDir = "docs"

# --- Blowfish 主题设置 ---
[params]
  colorScheme = "blowfish" 
  defaultBackgroundImage = "img/background.jpg"

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Inicio "
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "descripcion"
    name = "Descripción"
    url = "/#descripcion"  # 点击后网页会滑动到 id="descripcion" 的部分
    weight = 2
  [[menu.main]]
    identifier = "video"
    name = "vídeo "
    url = "/#video"
    weight = 3
  [[menu.main]]
    identifier = "interact"
    name = "interact "
    url = "#interact"
    weight = 4













[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true